### ISSUE TITLE
Documentation Use Case: 5G Media Streaming End to End Setup

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/Getting-Started#48]
Several improvements for consideration:
In https://github.com/5G-MAG/Documentation-and-Architecture/wiki/Use-Case:-5G-Media-Streaming---End-to-End-Setup#3-running-the-application-server:
Add:
```
mkdir ~/.rt_5gms
cat > ~/.rt_5gms/application-server.conf <<EOF

EOF
mkdir -p /tmp/rt-5gms-as/cache
mkdir /tmp/rt-5gms-as/logs
```
so that the file is created with the right configuration or just specify the path to the application-server.conf (if already exist) and indicate the change of the m3listen to the local IP address.

In https://github.com/5G-MAG/Documentation-and-Architecture/wiki/Use-Case:-5G-Media-Streaming---End-to-End-Setup#4--running-the-application-function, in the "Creating a content hosting configuration", the output of `~/rt-5gms-application-function/install/bin/m1-session list -v` should return the ipaddress specified in the yaml, right? In the previous part we changed it from localhost to 192.168.178.55. This should be the one listed. Just for consistency.

In Option 2 https://github.com/5G-MAG/Documentation-and-Architecture/wiki/Use-Case:-5G-Media-Streaming---End-to-End-Setup#2-starting-the-webserver, there may be some dependencies: install npm and some modules like npm install express

**Comment by jordijoangimenez** [comment]
For the first comment, perhaps just say that a config file is needed. I was just proposing this to be consistent with https://github.com/5G-MAG/rt-5gms-application-server/blob/main/docs/README.md

**Comment by dsilhavy** [comment]
Thanks @jordijoangimenez . Most of the comments are obsolete now that we are using `M8` with the `msaf-configuration` tool and `domainNameAlias` instead of `canonicalDomainName`.

I addressed your comment on the missing `npm install`.

**Comment by jordijoangimenez** [comment]
Some remarks:
The JSON with the streams should be called "streams.js" and stored in the same /etc/rt-5gms folder, right? This is not mentioned in "Now we define a JSON file with the streams:"

localhost/m8.json shows me (sorry for the format):
```
m5BaseUrl | "http://192.168.11.20:7778/3gpp-m5/v2/"
serviceList |  
0 |  
provisioningSessionId | "8325ab0a-e5e0-41ed-90b8-b31ef89d1498"
name | "VoD: Llama Drama"
entryPoints |  
0 |  
locator | "http://192.168.11.20/m4d/provisioning-session-8325ab0a-e5e0-41ed-90b8-b31ef89d1498/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=mpd-time-csf)"
contentType | "application/dash+xml"
profiles |  
0 | "urn:mpeg:dash:profile:isoff-live:2011"
1 |  
locator | "http://192.168.11.20/m4d/provisioning-session-8325ab0a-e5e0-41ed-90b8-b31ef89d1498/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl-v3)"
contentType | "application/vnd.apple.mpegurl"
```

The 5GMSd Aware application shows in the drop menu VoD:Llama Drama. However no content is displayed (an attempt to BUFFERING and then IDLE). Is it possible to get the config file of the BigBugBunny to test?
I've retrieved the mpd from the microsoft site and it comes through.

**Comment by jordijoangimenez** [comment]
This issue was solved by @davidjwbbc here: https://github.com/5G-MAG/rt-5gms-application-server/pull/69
