### ISSUE TITLE
Documentation: Add specifications for UE data collection, reporting and event exposure

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Getting-Started#83]
## Description
Similar to what we are doing for the other main projects like 5G Media Streaming we should list the relevant specifications for UE data collection, reporting, and event exposure.

* Example: https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/specifications.html
* Currently missing here: https://5g-mag.github.io/Getting-Started/pages/ue-data-collection-reporting-exposure/

**Comment by rjb1000** [comment]
I think the relevant specifications are:
* SA2:
  * Stage 2
     * TS 23.288 Architecture enhancements for 5G System (5GS) to support network data analytics services
* SA4:
  * Stage 2:
    * TS 26.531 Data Collection and Reporting; General Description and Architecture
  * Stage 3:
    * TS 26.532 Data Collection and Reporting; Protocols and Formats
* CT3:
  * Stage 3:
     * TS 29.517 5G System; Application Function Event Exposure Service; Stage 3

**Comment by dsilhavy** [comment]
Thanks @rjb1000 . The information is added in this PR: https://github.com/5G-MAG/Standards/pull/142. It needs to be linked to the docs generated by this repository once merged.

**Comment by jordijoangimenez** [comment]
Thanks @rjb1000 @dsilhavy. I'm going to link now the Getting-Started page

**Comment by dsilhavy** [comment]
@jordijoangimenez I just did :) You shouldn't work, enjoy your vacation :)
